import { Category } from './category.model';
import { News } from './news.model';
import { NewsMedia } from './newsMedia.model';
import { NewsVideo } from './newsVideo.model';
import { User } from './users.model';
import { Ads } from './ads.model';
import { Menu } from './menu.model';
import { YoutubeVideo } from './youtubeVideos.model';
import { Video } from './videos.model';
export { Category, News, NewsMedia, NewsVideo, User, Ads, Menu, YoutubeVideo, Video };
